name: Smoke-Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-smoke-test-on-each-push-to-main:
    container:
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Executing Smoke Tests
        run:  mvn clean test -Ppr-checks