name: Smoke-Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-smoke-test-on-each-push-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Selenoid
        uses: Xotabu4/selenoid-github-action@v2
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.11.3
          args: -limit 3
          browsers: chrome
          last-versions: 1


      - name: Executing Smoke Tests
        run: mvn clean test -Ppr-checks -DseleniumGridEnabled=true