name: Smoke-Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: run-smoke-test

    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World"
        # run:  cat /etc/os-release

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v1
      #   timeout-minutes: 10
      #   with:
      #     java-version: 11

      # - name: Run unit test
      #   timeout-minutes: 10
      #   run: mvn clean test -P pr-checks
      
